services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    container_name: web
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    stdin_open: true # docker run -i
    tty: true # docker run -t

    volumes:
      - .:/app

    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}

    profiles:
      - web

  terminal:
    build:
        context: .
        dockerfile: Dockerfile.dev
    container_name: terminal
    stop_signal: SIGINT
    stdin_open: true # docker run -i
    tty: true # docker run -t

    entrypoint: "python main.py"

    volumes:
      - .:/app

    profiles:
      - terminal
