name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: docker/build-push-action@v6
      with:
        file: Dockerfile.dev
        context: .
        push: false
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
