name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
      with:
        file: Dockerfile
        context: .
        push: false
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
