name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        context: .
        push: false
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
