name: Release

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - uses: docker/build-push-action@v5
      with:
        file: Dockerfile.dev
        context: .
        push: true
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
          stefanmich/spotifyrandomalbum:latest
