name: Release

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - uses: docker/build-push-action@v6
      with:
        file: Dockerfile.dev
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
          stefanmich/spotifyrandomalbum:latest
